include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_required_param: warning
    missing_return: warning
    todo: ignore

linter:
  rules:
    - prefer_single_quotes
    - avoid_empty_else
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - curly_braces_in_flow_control_structures
    - empty_catches
    - eol_at_end_of_file
    - file_names
    - use_full_hex_values_for_flutter_colors
    - prefer_expression_function_bodies
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_lambdas
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_statements
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unnecessary_this
    - always_use_package_imports
    - avoid_relative_lib_imports
    - avoid_function_literals_in_foreach_calls
    - camel_case_types
    - constant_identifier_names
    - prefer_const_declarations